import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, BarChart3, Bot, Cloud, Server, ShieldCheck, Workflow } from "lucide-react";
import { Breadcrumbs } from "@/components/ui/Breadcrumbs";
import { createMetadata } from "@/lib/seo";

export const metadata: Metadata = createMetadata({ title: "Sobre a Creativity", description: "Conheça a Creativity, empresa brasileira que conecta infraestrutura, cloud, segurança, dados, BI, IA, software e suporte.", path: "/sobre" });
const capabilities = [[Server, "Infraestrutura"], [Cloud, "Cloud e produtividade"], [ShieldCheck, "Segurança e continuidade"], [BarChart3, "Dados e BI"], [Bot, "IA e automação"], [Workflow, "Software e integrações"]] as const;
const principles = [["Problema antes do produto", "A recomendação começa pelo impacto na operação e pela decisão que precisa melhorar."], ["Conexão entre as frentes", "Infraestrutura, segurança, cloud, dados e software são tratados como partes da mesma evolução."], ["Governança e adoção", "A solução precisa ser segura, operável, compreendida e usada pelas pessoas certas."], ["Evolução sem improviso", "Prioridades, dependências e próximos ciclos ficam claros para a gestão."]];

export default function AboutPage() { return <>
  <section className="bg-neutral-950 py-16 text-white md:py-24"><div className="mx-auto max-w-[1280px] px-5 sm:px-8"><div className="[&_a]:text-neutral-400 [&_span]:text-neutral-400"><Breadcrumbs items={[{ label: "Sobre" }]} /></div><p className="mt-8 text-sm font-semibold uppercase text-teal-300">Sobre a Creativity</p><h1 className="mt-4 max-w-5xl text-4xl font-semibold leading-tight sm:text-5xl lg:text-6xl">Uma empresa de tecnologia para conectar o que sustenta, protege e orienta a operação.</h1><p className="mt-6 max-w-3xl text-base leading-8 text-neutral-300 sm:text-lg">A Creativity atua da infraestrutura à inteligência, organizando tecnologia como capacidade de negócio: disponível, segura, integrada, mensurável e preparada para evoluir.</p></div></section>
  <section className="bg-white py-16 md:py-24"><div className="mx-auto grid max-w-[1280px] gap-12 px-5 sm:px-8 lg:grid-cols-[0.8fr_1.2fr]"><div><p className="text-sm font-semibold uppercase text-blue-600">Nosso papel</p><h2 className="mt-4 text-4xl font-semibold leading-tight text-neutral-950">Transformar decisões técnicas em uma agenda clara para a empresa.</h2><p className="mt-5 text-base leading-8 text-neutral-600">Não existe valor em empilhar ferramentas. O trabalho é entender contexto, dimensionar o que faz sentido e conduzir a evolução com responsabilidade técnica e linguagem de gestão.</p></div><div className="grid gap-px overflow-hidden rounded-lg border border-neutral-200 bg-neutral-200 sm:grid-cols-2">{capabilities.map(([Icon, label]) => <div className="flex items-center gap-4 bg-white p-6" key={label}><span className="grid h-10 w-10 place-items-center rounded-md bg-blue-50 text-blue-600"><Icon className="h-5 w-5" /></span><span className="font-semibold text-neutral-950">{label}</span></div>)}</div></div></section>
  <section className="bg-[#e8f1ff] py-16 md:py-24"><div className="mx-auto max-w-[1280px] px-5 sm:px-8"><p className="text-sm font-semibold uppercase text-blue-700">Princípios de trabalho</p><div className="mt-8 border-t border-blue-200">{principles.map(([title, description]) => <div className="grid gap-3 border-b border-blue-200 py-6 sm:grid-cols-[0.45fr_1fr]" key={title}><h2 className="text-xl font-semibold text-neutral-950">{title}</h2><p className="text-sm leading-7 text-neutral-700">{description}</p></div>)}</div></div></section>
  <section className="bg-blue-600 py-16 text-white"><div className="mx-auto flex max-w-[1280px] flex-col gap-6 px-5 sm:px-8 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="text-3xl font-semibold">Vamos organizar o próximo passo?</h2><p className="mt-2 text-blue-100">Comece com um diagnóstico rápido do cenário atual.</p></div><Link className="inline-flex min-h-12 items-center justify-center gap-2 rounded-md bg-white px-6 py-3 text-sm font-semibold text-neutral-950" href="/diagnostico">Fazer diagnóstico <ArrowRight className="h-4 w-4" /></Link></div></section>
  </>; }
