import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Factory, PackageSearch, Sprout } from "lucide-react";
import { Breadcrumbs } from "@/components/ui/Breadcrumbs";
import { createMetadata } from "@/lib/seo";

export const metadata: Metadata = createMetadata({ title: "Casos e Cenários de Solução", description: "Conheça cenários demonstrativos de como a Creativity estrutura desafios, soluções e critérios de resultado.", path: "/cases" });

const cases = [
  { icon: Factory, segment: "Indústria", context: "Operação com dados comerciais, financeiros e produtivos em fontes diferentes.", challenge: "A diretoria recebe indicadores depois do fechamento e cada área explica os números com uma regra própria.", approach: ["Inventariar fontes e decisões prioritárias", "Definir regras e responsabilidades dos indicadores", "Integrar dados e publicar uma visão executiva", "Acompanhar adoção, qualidade e novas perguntas"], outcome: "Uma base gerencial comum, com origem e atualização conhecidas." },
  { icon: PackageSearch, segment: "Distribuição", context: "Operação de alto volume com estoque, carteira, crédito, margem e logística.", challenge: "O excesso aparece em uma planilha, o risco de carteira em outra e a margem somente depois da venda.", approach: ["Priorizar produtos, clientes e unidades críticas", "Conectar ERP, planilhas e fontes autorizadas", "Criar alertas para exceções relevantes", "Evoluir para previsão conforme a qualidade do histórico"], outcome: "Sinais consolidados para priorizar estoque, margem e atendimento." },
  { icon: Sprout, segment: "Agronegócio", context: "Distribuição de insumos com dinâmica por safra, cultura, região, produtor e unidade.", challenge: "Comparações mensais não explicam o ciclo e dificultam relacionar venda, custo, crédito e disponibilidade.", approach: ["Modelar a operação pela lógica de safra", "Relacionar comercial, estoque e financeiro", "Criar visões por unidade, cultura e carteira", "Validar indicadores com quem decide e opera"], outcome: "Uma leitura gerencial aderente à complexidade do negócio." },
];

export default function CasesPage() {
  return <>
    <section className="bg-[#f3f5f7] py-16 md:py-24"><div className="mx-auto max-w-[1280px] px-5 sm:px-8"><Breadcrumbs items={[{ label: "Cases" }]} /><p className="mt-8 text-sm font-semibold uppercase text-blue-600">Estrutura de casos</p><h1 className="mt-4 max-w-5xl text-4xl font-semibold leading-tight text-neutral-950 sm:text-5xl lg:text-6xl">Desafio, abordagem e resultado esperado. Sem história fabricada.</h1><p className="mt-6 max-w-3xl text-base leading-8 text-neutral-600 sm:text-lg">Enquanto os casos reais aguardam autorização formal para publicação, mostramos cenários demonstrativos para explicar como pensamos e executamos.</p></div></section>
    <section className="bg-white py-16 md:py-24"><div className="mx-auto grid max-w-[1280px] gap-6 px-5 sm:px-8">{cases.map((item) => { const Icon = item.icon; return <article className="rounded-lg border border-neutral-200 p-6 sm:p-8" key={item.segment}><div className="flex flex-col gap-5 border-b border-neutral-200 pb-6 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-4"><span className="grid h-12 w-12 place-items-center rounded-md bg-blue-50 text-blue-600"><Icon className="h-6 w-6" /></span><div><p className="text-xs font-semibold uppercase text-blue-600">Cenário demonstrativo</p><h2 className="mt-1 text-2xl font-semibold text-neutral-950">{item.segment}</h2></div></div><span className="self-start rounded-md bg-amber-50 px-3 py-2 text-xs font-semibold text-amber-800">Não representa cliente real</span></div><div className="mt-7 grid gap-7 lg:grid-cols-[0.8fr_0.8fr_1fr_0.8fr]"><CaseBlock title="Contexto" text={item.context} /><CaseBlock title="Desafio" text={item.challenge} /><div><h3 className="text-xs font-semibold uppercase text-neutral-500">Abordagem</h3><ol className="mt-3 grid gap-2 text-sm leading-6 text-neutral-700">{item.approach.map((step, index) => <li className="flex gap-3" key={step}><span className="font-semibold text-blue-600">{index + 1}.</span>{step}</li>)}</ol></div><CaseBlock title="Resultado esperado" text={item.outcome} /></div></article>; })}</div></section>
    <section className="bg-neutral-950 py-16 text-white"><div className="mx-auto flex max-w-[1280px] flex-col gap-6 px-5 sm:px-8 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="text-3xl font-semibold">Seu cenário pode ser o ponto de partida.</h2><p className="mt-2 text-neutral-400">Vamos entender o desafio sem presumir a solução.</p></div><Link className="inline-flex min-h-12 items-center justify-center gap-2 rounded-md bg-teal-400 px-6 py-3 text-sm font-semibold text-neutral-950" href="/contato">Conversar com a Creativity <ArrowRight className="h-4 w-4" /></Link></div></section>
  </>;
}

function CaseBlock({ title, text }: { title: string; text: string }) { return <div><h3 className="text-xs font-semibold uppercase text-neutral-500">{title}</h3><p className="mt-3 text-sm leading-7 text-neutral-700">{text}</p></div>; }

